# ---------------------------
# Components
# ---------------------------

# ---------------------------
# Aliases
# ---------------------------
zv() {
  local prev="$PWD"
  z "$1" || return
  nvim .
  cd "$prev"
}

ziv() {
  local prev="$PWD"
  zi || return
  nvim .
  cd "$prev"
}

alias lock='hyprlock'
alias hibernate='systemctl hibernate'
alias suspend='systemctl suspend'
alias reboot='systemctl reboot'
alias poweroff='systemctl poweroff'
alias logout='loginctl terminate-session "$XDG_SESSION_ID"'

# ---------------------------
# Environment
# ---------------------------

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

eval "$(fzf --zsh)"
eval "$(zoxide init zsh)"

# ---------------------------
# Prompt config
# ---------------------------
if [[ -o interactive ]]; then
  eval "$(starship init zsh)"
else
  setopt PROMPT_SUBST

  git_prompt() {
    git rev-parse --is-inside-work-tree &>/dev/null || return

    local b s
    b=$(git symbolic-ref --quiet --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
    s=$(git status --porcelain 2>/dev/null)

    printf " %%{\e[35m%%}%s%s%%{\e[0m%%}" "$b" "$( [ -n "$s" ] && printf "*" )"
  }

  PS1=$'\n%{$( [ $? -ne 0 ] && printf "\e[31m%d\e[0m " $? )%}%{\e[36m%}%~%{\e[0m%}$(git_prompt) %{\e[90m%}\n›%{\e[0m%} '
fi
