{
  cfg,
  pkgs,
  lib,
  quickshellStoreDir,
  setXftDpi,
}:

with lib;
let
  layout = cfg.hyprland.layout;

  hyprMonitor =
    name: d:
    let
      outputName = if name == "" then "" else name;
      mode = if d.hz != null then "${d.res}@${toString d.hz}" else d.res;
    in
    ''
      hl.monitor({
          output = "${outputName}",
          mode = "${mode}",
          position = "${toString d.position.x}x${toString d.position.y}",
          scale = ${toString d.scale},
      })'';

  hyprSpecialWsRules =
    name: ws:
    let
      matches = mapAttrsToList (k: vs: {
        key = if k == "app_id" then "class" else k;
        value = concatStringsSep "|" vs;
      }) ws.rule;
      mkRule =
        m:
        "hl.window_rule({ match = { ${m.key} = \"${m.value}\" }, workspace = \"special:${name} silent\"${
          optionalString (layout == "scrolling") ", scrolling_width = 1.0"
        } })";
    in
    concatMapStringsSep "\n" mkRule matches;

  hyprSpecialWsBind =
    name: ws: ''hl.bind(mod .. " + ${ws.key}", hl.dsp.workspace.toggle_special("${name}"))'';

  specialWsAutostarts = concatStringsSep "\n" (
    mapAttrsToList (
      _: ws: optionalString ws.autostart ''hl.exec_cmd("${ws.startCommand}")''
    ) cfg.specialWorkspaces
  );

  displaysList = mapAttrsToList (n: v: {
    name = n;
    value = v;
  }) cfg.displays;
  specialWsList = mapAttrsToList (n: v: {
    name = n;
    value = v;
  }) cfg.specialWorkspaces;
in
pkgs.writeText "hyprland-config" ''
  -- Minima | Hyprland config (generated by minima-shell)

  -- Layout & plugin setup
  local hy3 = hl.plugin.hy3
  local layoutName = "${layout}"

  ${optionalString (layout == "hy3") ''
    if hy3 == nil then
      layoutName = "dwindle"
      hl.notification.create({ text = "hy3 plugin failed to load, falling back to dwindle", timeout = 10000 })
    end
  ''}

  hl.config({ general = { layout = layoutName } })

  -- Variables
  local mod = "SUPER"
  local terminal = "${cfg.programs.terminal.name}"
  local browser = "${cfg.programs.browser.name}"
  local fileManager = "${cfg.programs.fileManager.name}"
  local qs_path = "${quickshellStoreDir}"

  -- Monitors
  ${concatMapStringsSep "\n" (x: hyprMonitor x.name x.value) displaysList}

  -- Workspace assignment
  ${concatMapStringsSep "\n" (
    x:
    ''hl.workspace_rule({ workspace = "${toString x.value.workspace}", monitor = "${x.name}", default = true })''
  ) (filter (x: x.value.workspace != null) displaysList)}

  -- Special workspaces
  ${concatMapStringsSep "\n" (x: hyprSpecialWsRules x.name x.value) specialWsList}
  ${concatMapStringsSep "\n" (x: hyprSpecialWsBind x.name x.value) specialWsList}

  -- Keybinds
  ${import ./config.d/keybinds.nix { inherit layout pkgs; }}
  ${builtins.readFile ./config.d/workspace.lua}
  ${import ./config.d/application-behavior.nix { inherit layout; }}
  ${builtins.readFile ./config.d/env.lua}
  ${builtins.readFile ./config.d/input.lua}
  ${import ./config.d/application-style.nix { inherit layout; }}

  -- Autostart
  hl.on("hyprland.start", function()
    ${concatMapStringsSep "\n" (a: ''hl.exec_cmd("${a}")'') cfg.autostart}
    ${specialWsAutostarts}
    hl.exec_cmd("${setXftDpi}")
    hl.exec_cmd("${pkgs.awww}/bin/awww-daemon")
    hl.exec_cmd("${pkgs.kdePackages.polkit-kde-agent-1}/libexec/polkit-kde-authentication-agent-1")
    hl.exec_cmd("wl-paste --watch cliphist store")
  end)

  -- Shell panel: killed and respawned on reload so a new generation takes effect.
  -- The running qs_path is stored to a file because it changes between generations;
  -- on the next start we kill the previously stored instance before launching the new one.
  local qsStateFile = "/tmp/minima-qs-path"
  local startShell = function()
    local oldPath = nil
    local f = io.open(qsStateFile, "r")
    if f then
      oldPath = f:read("*a")
      f:close()
      oldPath = oldPath:gsub("%s+", "")
    end

    if oldPath ~= nil and oldPath ~= "" then
      -- No duplicate check on kill: the old instance gets a graceful shutdown via IPC
      hl.exec_cmd("${pkgs.quickshell}/bin/qs -p " .. oldPath .. " kill")
    end

    local out = io.open(qsStateFile, "w")
    if out then
      out:write(qs_path)
      out:close()
    end

    hl.exec_cmd("${pkgs.coreutils}/bin/sleep 0.5 && exec ${pkgs.quickshell}/bin/qs -p " .. qs_path)
  end

  hl.on("hyprland.start", startShell)
  hl.on("config.reloaded", startShell)

  -- Sync keyboard layout with the system locale settings
  local syncKbLayout = function()
    local f = io.popen('localectl status | sed -n "s/^\\s*X11 Layout:\\s*//p"')
    if f == nil then return end
    local kbLayout = f:read("*a")
    f:close()
    kbLayout = kbLayout:gsub("%s+", "")
    if kbLayout ~= "" then
      hl.config({ input = { kb_layout = kbLayout } })
    end
  end

  hl.on("hyprland.start", syncKbLayout)
  hl.on("config.reloaded", syncKbLayout)
''
